### PR TITLE
Grouping components into catagories

### PR DESCRIPTION
**Pull request by bobbonius**
# Description

Together with design we added categories so we can group our components.

## How to test

- Checkout this branch
- `yarn storybook`
- Check if the categories are in the menu on the left

## Screenshots
080ec3f26583fa6eff78fa34c3d2ba64

### CODE REVIEW

**Comment by bobbonius** [comment]
We also had a discussion about renaming `BaseButton` to `Link` as we all thought they look more like a link.

**Comment by Roohn** [comment]
> We also had a discussion about renaming `BaseButton` to `Link` as we all thought they look more like a link.

It looks like a link, but is still a button. So I wouldn't call it link to avoid a lot of confusion 😬

**Comment by glenngijsberts** [comment]
I would display the `OnboardingDialog` at the same category as the `Dialog` component. Besides that, the `OnboardingDialog` has a duplicate story.

**Comment by glenngijsberts** [comment]
> > We also had a discussion about renaming `BaseButton` to `Link` as we all thought they look more like a link.
> 
> It looks like a link, but is still a button. So I wouldn't call it link to avoid a lot of confusion 😬

Also it would be conflicting with the `Link` from Next 😬

**Comment by Roohn** [comment]
The following categories are a bit meaningless to me:
- Surfaces
- Data display
- Layout
- Content
Every single component has a surface, displays data, has a layout and has content… 😅 
Could you maybe elaborate on the reason why you choose these?

**Review by RobVermeer — APPROVED** [review]
I think we can improve on the categories, but that will come over time, have no suggestions atm! Really nice though! 😄

**Review by glenngijsberts — APPROVED** [review]
Nice work 🤙

**Pull request merged**
