### PR TITLE
feat(callAll): Export the callAll util as we also want to use it in sirius

### PR DESCRIPTION
**Pull request by viktorrenkema**
# Description
In Sirius, we also have a callAll util. To keep things leaner, I want to remove it in sirius and get it from solar instead. After this PR is approved, I'll import it in sirius and replace the old util in sirius.

### CODE REVIEW

**Comment by bobbonius** [comment]
You can use `yarn commit` for semantic commits or change it manually to:

`'feat(callAll): Export the callAll util as we also want to use it in sirius'`

**Comment by bobbonius** [comment]
@viktorrenkema You need to change the commit, not the title of the PR 😬

**Comment by viktorrenkema** [comment]
> @viktorrenkema You need to change the commit, not the title of the PR 😬

Haha woops, thanks. Any reason why Solar requires semantic commits while Sirius does not?

**Comment by bobbonius** [comment]
> > @viktorrenkema You need to change the commit, not the title of the PR 😬
> 
> Haha woops, thanks. Any reason why Solar requires semantic commits while Sirius does not?

@viktorrenkema Solar is open source, so for good practice reasons I guess

**Review by bobbonius — APPROVED** [review]
😎

**Comment by glenngijsberts** [comment]
> > > @viktorrenkema You need to change the commit, not the title of the PR 😬
> > 
> > 
> > Haha woops, thanks. Any reason why Solar requires semantic commits while Sirius does not?
> 
> @viktorrenkema Solar is open source, so for good practice reasons I guess

and because it's a (NPM) package, which needs versioning. Semantic commits makes it easy to determine versions, generate release notes, etc.

**Review by glenngijsberts — APPROVED** [review]
👍 

Maybe nice to make your commit title a bit smaller, as you can see here it's already a bit too big for GitHub itself, and some other tools for git are also making it harder to read the commit message. For example, you could say `feat(callAll): export the callAll util` and then add the Sirius part in the body.

Also, since Solar is something on it's own (and open source) it can be a bit weird to mention Sirius here, because for people outside the company Sirius is unkown, so they are missing context.

Screenshot 2022-07-25 at 11 47 06

**Comment by viktorrenkema** [comment]
> feat(callAll): export the callAll util

Nice one, didn't think of that. Changed :)

**Pull request merged**
