### PR TITLE
fix: use correct colors for tooltip

### PR DESCRIPTION
**Pull request by glenngijsberts**
# Description

The colors of the tooltip weren't using the correct colors, so I've added proper background and foreground colors. Also scaled-down the tooltip, because it was a little too big imo.

@Marruk could you give feedback?

## How to test

- Checkout this branch
- `$ yarn storybook`
- Search for Tooltip
- Verify it's working

## Screenshots

Before
Screenshot 2022-03-31 at 14 58 33

After

Screenshot 2022-03-31 at 18 22 06
Screenshot 2022-03-31 at 18 22 23

### CODE REVIEW

**Comment by Marruk** [comment]
I would be in favour of using `invertedBackground` and `invertedForeground`, the goal of the tooltip is to have a lot of contrast with whatever background it is on. @julimpaiva what do you think?

**Comment by Julimpaiva** [comment]
> 

Makes sense, so would be the opposite of the bg that is in.

**Comment by glenngijsberts** [comment]
@Julimpaiva @Marruk thanks for the feedback :) Applied it!

What do you both think of the size of the tooltip?

**Review by Roohn — APPROVED** [review]

**Comment by Julimpaiva** [comment]
> 

Size looks good. It takes the size of text plus the padding right?

**Comment by glenngijsberts** [comment]
> > 
> 
> Size looks good. It takes the size of text plus the padding right?

@Julimpaiva yes! thanks :)

**Pull request merged**
