### PR TITLE
Refactor Image component

### PR DESCRIPTION
**Pull request by rppld**
Adds a few improvements such as feature detection for native lazy-loading.

⚠️ Merge https://github.com/TicketSwap/solar/pull/514 first and rebase to adjust `<Image />` in Card component.

### CODE REVIEW

**Review by luciatoma — APPROVED** [review]

**Review by lucasfeliciano — APPROVED** [review]
Nice!

Thanks for adding propTypes

**Review by glenngijsberts — APPROVED** [review]

**Comment by rppld** [comment]
Don’t spread props onto `<figure />` element.

**Comment by rppld** [comment]
Replace `.currentSrc` with `.getAttribute("src")`

**Comment by rppld** [comment]
`initialVisible` should be `true` during SSR.

**Pull request closed without merging**
