### PR TITLE
Card component updates

### PR DESCRIPTION
**Pull request by rppld**
# Description

Also adjusts line-heights and spacings slightly.

## How to test

- Checkout this branch
- `$ yarn dev`

### CODE REVIEW

**Review by luciatoma — APPROVED** [review]
Looks really good! 

My only suggestions would be for the `Pill` with the number of available tickets to maybe be centered more with the text? (looks a little bit too high compared with the texts in its left)

Screenshot 2019-12-27 at 14 33 58

Screenshot 2019-12-27 at 14 34 10

**Comment by rppld** [comment]
> My only suggestions would be for the Pill with the number of available tickets to maybe be centered more with the text? (looks a little bit too high compared with the texts in its left)

@luciatoma that’s intentional, see attached screenshot. The vertical alignment of text-content can be controlled with the new `verticalAlign` prop, but in this case it should be aligned at the top.

**Review by glenngijsberts — APPROVED** [review]
LGTM!

**Pull request merged**
